### ISSUE TITLE
Usar evento "input" no lugar do "keypress"

### ISSUE THREAD

**Issue by fdaciuk** [clarabatt/form-masks#1]
[Nessa linha](https://github.com/clarabatt/form-masks/blob/master/main.js#L4) dá pra usar um evento "input", que é disparado sempre que uma tecla é pressionada. Apesar de não ter suporte para IE8 ou menos, ele é recomendado no lugar de usar o "keypress".

Mas acho que não dar suporte para ie8- não é um problema né xD

**Comment by clarabatt** [comment]
Tá trocado :)
