### ISSUE TITLE
Abstrair o código para usar como uma library

### ISSUE THREAD

**Issue by fdaciuk** [clarabatt/form-masks#7]
Tem alguns passos que podemos seguir pra fazer esse código se tornar uma lib, com algumas funções pré-definidas, e poder receber qualquer tipo função que o usuário queira para fazer a máscara.

Começando da maneira mais simples, vamos só quebrar o código, mas mantê-lo funcionando como está:
- [x] Renomear o `main.js` para um nome que faça sentido para a lib (`form-masks.js` talvez);
- [x] Separar o código da linha `3` até a linha `16` em um outro arquivo (pode ser um `main.js`). O `form-masks.js` será a nossa lib, e o `main.js` será o arquivo que poderá ter em qualquer projeto, e poderá ter qualquer conteúdo. É nele que vamos **usar** a lib :)
- [x] Depois de separar, é necessário exportar a função `mascara` para ser usada em outro arquivo, já que ela está dentro de uma IIFE e não pode ser acessada de fora. Já dá pra aproveitar aqui e renomear essa função para `formMasks`, que será a função principal da lib. Feito isso, no final do arquivo, ainda dentro da IIFE, exporte a função `formMasks`, usando o objeto `window`. Ao fazer isso, será necessário modificar a chamada de `mascara` no arquivo `main.js` para `formMasks`.

Feito isso, a primeira parte do refactory vai estar pronta! Se tudo continuar funcionando daqui, continuamos os próximos passos :D

**Comment by fdaciuk** [comment]
ping @clarabatt

**Comment by clarabatt** [comment]
@fdaciuk essa questão de exportar a função é modulação de código?

**Comment by fdaciuk** [comment]
Isso mesmo! Assim você consegue usar esse código como uma biblioteca em qualquer projeto =)

**Comment by clarabatt** [comment]
Mas no segundo arquivo o código fica dentro de uma IIFE também?

**Comment by fdaciuk** [comment]
Isso mesmo! A diferença é que a lib você precisa exportar para ser usada no escopo global. Você pode usar, dentro da IIFE do `form-masks.js`, algo como (no final do arquivo):

``` js
window.formMasks = formMasks;
```

Assim você consegue acessar a função `formMasks` de outros arquivos, e ela poderá funcionar como uma lib =)

**Comment by clarabatt** [comment]
Não funcionou não :laughing: 
Uma coisa que não ficou muito clara, como o main.js vai ser chamado? Por JS ou pelo index.html mesmo?

**Comment by fdaciuk** [comment]
É que você não adicionou o script `main.js` no `index.html` ;)

e o `formMasks`, vc pode passar como parâmetro na IIFE, para usá-lo no `main.js` como uma variável local:

``` js
(window, document, window.formMasks)
```

A estrutura vai ser essa:
- A sua lib vai ser o `form-masks.js`
- O seu projeto (qualquer que seja), vai ser o `index.html` e o `main.js`.

A ideia é poder usar o `form-masks.js` em qualquer projeto =)

Sacou? xD

**Comment by clarabatt** [comment]
Ahhhhh, saquei! Faltou exportar as outras funções, por isso não tava funcionando.

**Comment by fdaciuk** [comment]
Na verdade, faltou importar o form masks no teu projeto. Adicionar ele na index.html e chamar no main.js =)

**Comment by fdaciuk** [comment]
Mas a ideia é essa mesmo :D

**Comment by woliveiras** [comment]
@fdaciuk tem alguma maneira de deixar as funções   `cpfFormat`, `rgFormat`, `telFormat`, `celFormat`, `cepFormat` dentro de `formMasks`?

**Comment by fdaciuk** [comment]
@woliveiras mas não está? xD

**Comment by woliveiras** [comment]
Opa, eu mosquei nessa dúvida mano. Ainda não tinha reparado legal no código nessa parte aqui:

```
  function formMasks( objeto, funcao ){
    var obj = objeto.value;
    var func = funcao;
    objeto.value = exec( obj, func );
  }
```

Recebe o `objeto` que vai ser tratado e a `funcao` que vai tratar.

Eu quiz dizer se tivesse outra maneira de executar a lib sem fazer assim:

```
$cpf.addEventListener( 'input', function(){ formMasks( $cpf, cpfFormat ) }, false );
```

Sem precisar passar a função `cpfFormat` como parâmetro.

**Comment by fdaciuk** [comment]
Entendi.. na real, essa foi uma forma que a lib foi criada.. daria pra pensar em outras assinaturas pra ela, e depois codar em cima disso.

Algo no estilo de outras libs de máscara:

``` js
formMasks($nodeCpf, '999.999.999-99')
```

E usar alguns caracteres coringa: `9` será sempre número, `?` é opcional, etc. E depois codar em cima dessa ideia =)

**Comment by woliveiras** [comment]
Passar o pattern que vai ser usado no lugar de qual função chamar né?

**Comment by fdaciuk** [comment]
Isso.. esse é meio que o padrão das libs hoje.. daria pra pensar em outras assinaturas, mas essa é a mais comum.

**Comment by woliveiras** [comment]
Shooow
